# Generated by Django 3.2 on 2025-05-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=100)),
                ('plat_nomor', models.CharField(max_length=15)),
                ('harga_sewa_per_hari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tersedia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_ktp', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_sewa', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('total_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.motor')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.pelanggan')),
            ],
        ),
    ]
