# Generated by Django 3.2 on 2025-05-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(default='aktif', max_length=20),
        ),
    ]
