# Generated by Django 3.2 on 2025-05-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='status_pengembalian',
            field=models.BooleanField(default=False),
        ),
    ]
