# Generated by Django 3.2 on 2025-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_pelanggan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
