# Generated by Django 3.2 on 2025-05-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_transaksi_status_pengembalian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=100),
            preserve_default=False,
        ),
    ]
