# Generated by Django 3.2 on 2025-05-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_pelanggan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
