# Generated by Django 3.2 on 2025-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_pelanggan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='jenis_kelamin',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
