# Generated by Django 3.2 on 2025-07-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_pelanggan_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='jumlah_unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
